// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrYpWmIjpk1xl3Rp1X2GGZjKe5Kpg38YA',
    appId: '1:104400851378:web:997b909ee063286117d4ab',
    messagingSenderId: '104400851378',
    projectId: 'weather-app-4107a',
    authDomain: 'weather-app-4107a.firebaseapp.com',
    storageBucket: 'weather-app-4107a.firebasestorage.app',
    measurementId: 'G-1JCEW5TSJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOzmb0hgzy9Clg1C1I863cUHeIPlh6L-o',
    appId: '1:104400851378:android:594563125382941e17d4ab',
    messagingSenderId: '104400851378',
    projectId: 'weather-app-4107a',
    storageBucket: 'weather-app-4107a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDocldVwvzm8PaWGflKRH_8oAaA-3EOJck',
    appId: '1:104400851378:ios:8f83cc2cc94f5b1817d4ab',
    messagingSenderId: '104400851378',
    projectId: 'weather-app-4107a',
    storageBucket: 'weather-app-4107a.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDocldVwvzm8PaWGflKRH_8oAaA-3EOJck',
    appId: '1:104400851378:ios:8f83cc2cc94f5b1817d4ab',
    messagingSenderId: '104400851378',
    projectId: 'weather-app-4107a',
    storageBucket: 'weather-app-4107a.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrYpWmIjpk1xl3Rp1X2GGZjKe5Kpg38YA',
    appId: '1:104400851378:web:85d2fe5a9fcea3cc17d4ab',
    messagingSenderId: '104400851378',
    projectId: 'weather-app-4107a',
    authDomain: 'weather-app-4107a.firebaseapp.com',
    storageBucket: 'weather-app-4107a.firebasestorage.app',
    measurementId: 'G-HMD7V8HT1C',
  );
}
